### ISSUE TITLE
Get project to run

### ISSUE THREAD

**Issue by NuroC** [timofriedl/javaABC-ai-population#1]
Hey ich wuerde gerne meine eigene simulation starten hab aber keine ahnung wie ich das java projekt zum laufen bringe. Kannst du vllt irgendwie ne readme machen oder kurz in schnellen schritten erklaeren wie man das ganze zum laufen bringt?

**Comment by timofriedl** [comment]
Hi, das Projekt ist aktuell tatsächlich sehr schlecht dokumentiert. Ich hab aktuell leider keine Zeit dafür aber nächste Woche setz ich mich mal ran :)

**Comment by NuroC** [comment]
Habs selber geschafft, wenn du willst kann ich ne PR mit ner kleinem readme machen ;-)

**Comment by Tro-asa** [comment]
Ich fände es super, wenn du das machen könntest xD
